version: 0.2

phases:
  build:
    commands:
      - echo "Processing mock test results"

reports:
  junit_reports:
    files:
      - "mock.xml"
      - "mock2.xml"
      - "mock_no_testsuitename.xml"
      - "mock_empty_string_testsuitename.xml"
    file-format: "JUNITXML"

